controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#app_platform_home:
#  path: /
#  controller: App\Controller\PlatformController::home
#
#app_platform_holidayrequest:
#  path: /request
#  controller: App\Controller\PlatformController::request
